from dataclasses import dataclass
from typing import Optional

from cronwatch.notifiers.base import AlertPayload, BaseNotifier


@dataclass
class BearyyChatConfig:
    webhook_url: str
    channel: Optional[str] = ...
    bot_name: str = ...
    timeout: int = ...


class BearyChatNotifier(BaseNotifier):
    def __init__(self, config: BearyyChatConfig) -> None: ...
    def send(self, payload: AlertPayload) -> None: ...
    def _build_message(self, payload: AlertPayload) -> dict: ...
