from dataclasses import dataclass
from typing import List, Optional

from cronwatch.notifiers.base import AlertPayload, BaseNotifier

@dataclass
class GrafanaConfig:
    url: str
    api_key: Optional[str] = ...
    tags: List[str] = ...
    timeout: int = ...

class GrafanaNotifier(BaseNotifier):
    config: GrafanaConfig

    def __init__(self, config: GrafanaConfig) -> None: ...
    def send(self, payload: AlertPayload) -> None: ...
    def _build_event(self, payload: AlertPayload) -> dict: ...
