from dataclasses import dataclass, field
from typing import Optional

from cronwatch.notifiers.base import AlertPayload, BaseNotifier

@dataclass
class LinearConfig:
    api_key: str
    team_id: str
    assignee_id: Optional[str] = ...
    priority: int = ...
    label_ids: list[str] = ...
    def __post_init__(self) -> None: ...

class LinearNotifier(BaseNotifier):
    def __init__(self, config: LinearConfig) -> None: ...
    def send(self, payload: AlertPayload) -> None: ...
    def _build_description(self, payload: AlertPayload) -> str: ...
