from dataclasses import dataclass, field
from typing import Optional
from cronwatch.notifiers.base import AlertPayload, BaseNotifier

@dataclass
class MatrixConfig:
    homeserver_url: str
    access_token: str
    room_id: str
    timeout: int = ...
    extra_headers: dict = ...
    def __post_init__(self) -> None: ...

class MatrixNotifier(BaseNotifier):
    def __init__(self, config: MatrixConfig) -> None: ...
    def send(self, payload: AlertPayload) -> None: ...
    def _build_message(self, payload: AlertPayload) -> dict: ...
