"""Type stubs for splunk_notifier."""

from dataclasses import dataclass, field
from typing import Optional

from cronwatch.notifiers.base import AlertPayload, BaseNotifier


@dataclass
class SplunkConfig:
    hec_url: str
    token: str
    index: Optional[str] = ...
    source: str = ...
    sourcetype: str = ...
    timeout: int = ...
    verify_ssl: bool = ...
    extra_fields: dict = ...


class SplunkNotifier(BaseNotifier):
    def __init__(self, config: SplunkConfig) -> None: ...
    def send(self, payload: AlertPayload) -> None: ...
    def _build_event(self, payload: AlertPayload) -> dict: ...
